version: "3.8"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: ./app
      target: development
    volumes:
      - ./app/src:/app/src
      - ./app/node_modules:/app/node_modules
      # - rf_fe_app_dependencies:/app/node_modules
    ports:
      - 5000:5000
volumes:
  rf_fe_app_dependencies: