version: "3.7"
services:
    rf-fe-preview:
        build:
            context: .
            dockerfile: Dockerfile.preview
        container_name: rf-fe-preview
        restart: unless-stopped
        networks:
            - proxy-bridge
        ports:
            - "5001:80"
networks:
    proxy-bridge:
        external: true
        name: proxy-bridge
