version: "3.7"
services:
    rf-fe-production:
        build:
            context: .
            dockerfile: Dockerfile.production
        container_name: rf-fe-production
        restart: unless-stopped
        networks:
            - proxy-bridge
        ports:
            - "5002:80"

networks:
    proxy-bridge:
        external: true
        name: proxy-bridge
